local root = vim.fn.getcwd()
local tmp = vim.fn.tempname(); vim.fn.mkdir(tmp .. "/app/cartridge/controllers", "p"); vim.fn.mkdir(tmp .. "/app/cartridge/templates/default", "p")
vim.fn.writefile({ '{"hostname":"example.com","username":"u","password":"p"}' }, tmp .. "/dw.json")
vim.fn.writefile({ "com.demandware.studio.core.beehiveNature" }, tmp .. "/app/.project")
vim.fn.writefile({ "server.get('Show', function () {});", "server.post(\"Save\", function () {});" }, tmp .. "/app/cartridge/controllers/Home.js")
vim.fn.writefile({ "<isprint value=\"${pdict.name}\"/>" }, tmp .. "/app/cartridge/templates/default/home.isml")
vim.cmd("set runtimepath^=" .. root); vim.cmd("runtime plugin/prophet.lua")
local config, sfcc, prophet = require("prophet.config"), require("prophet.sfcc"), require("prophet")
assert(config.root(tmp .. "/app/cartridge/controllers/Home.js") == tmp)
assert(config.load(tmp .. "/app").hostname == "example.com")
assert(#config.get_cartridges(tmp .. "/app") == 1)
assert(#sfcc.controllers(tmp .. "/app") == 2 and #sfcc.templates(tmp .. "/app") == 1)
assert(sfcc.candidates("URLUtils.")[1].word == "url")
for _, name in ipairs({ "ProphetControllers", "ProphetTemplates", "ProphetLogs", "ProphetRefresh" }) do assert(vim.fn.exists(":" .. name) == 2) end
assert(vim.fn.exists(":ProphetDebugConnect") == 0)
assert(vim.filetype.match({ filename = "x.isml" }) == "isml" and vim.filetype.match({ filename = "x.ds" }) == "ds")
local selected; vim.ui.select = function(items, opts, cb) assert(opts.prompt == "test"); cb(items[1]) end
prophet.default_picker({ title = "test", items = { { label = "one", path = tmp } }, select = function(i) selected = i.label end }); assert(selected == "one")
vim.fn.delete(tmp, "rf"); print("Prophet headless tests passed")
